### ISSUE TITLE
Form is not submitted

### ISSUE THREAD

**Issue by ameer-gaditek** [bitmash/alipay-api-php#2]
The same code I have used in form (with hidden fields) and after redirecting to alipay's site it shows illegal_sign error, why? is alipay not accepting for data? here is my code

<form method="get" id="frm" action="https://mapi.alipay.com/gateway.do?_input_charset=utf-8">
<input type="hidden" name="_input_charset" id="_input_charset" value="utf-8" />
<input type="hidden" name="body" id="body" value="test+amir" /><input type="hidden" name="currency" id="currency" value="USD" />
<input type="hidden" name="notify_url" id="notify_url" value="https%3A%2F%2Fmysite.com%2Fmypath%2Fgws%2Fcallback%2Falipay_callback.php" />
<input type="hidden" name="out_trade_no" id="out_trade_no" value="1433151789" />
<input type="hidden" name="partner" id="partner" value="MY LIVE ACCOUNT's PARTNER ID  />
<input type="hidden" name="payment_type" id="payment_type" value="1" />
<input type="hidden" name="return_url" id="return_url" value="https%3A%2F%2Fmysite.com%2Fmypath%2Fgws%2Fcallback%2Falipay_callback.php" /><input type="hidden" name="service" id="service" value="create_forex_trade" />
<input type="hidden" name="subject" id="subject" value="test+payment+123" />
<input type="hidden" name="total_fee" id="total_fee" value="10" /><input type="hidden" name="sign" id="sign" value="7e1aec789bf478b383de49e94cd74769" />
<input type="hidden" name="sign_type" id="sign_type" value="MD5" />
<input type="submit" />
</form>

**Comment by bitmash** [comment]
You never provided your code.

**Comment by big89** [comment]
Hello, am using this code for alipay demo but its giving me same error as above...can u help me with this ?

Thanks

**Comment by bitmash** [comment]
@ameer-gaditek @big89 I updated the code. Try using it and it should solve your issues.
