### ISSUE TITLE
transaction error

### ISSUE THREAD

**Issue by adrianmak** [bitmash/alipay-api-php#3]
I tried the transaction.php test code.
I clicked the "Test Transaction Link", alipay return an error
创建交易错误
输入参数错误! 
In English, 
Transaction creation error
Wrong input parameters!

**Comment by bitmash** [comment]
Ignore the test links. Those no longer apply. They now have a sandbox environment (see README.md). 

Also, they now require the `currency` parameter when calling `createPayment()`. This parameter depends on your contract with Alipay. In my case it would be "USD".
