### ISSUE TITLE
use alipay for verifying transaction

### ISSUE THREAD

**Issue by yfsx** [bitmash/alipay-api-php#4]
hi, thanks for sharing this lib!

can i use this lib if i just only want to verify the payment from alipay? which function should i used and which data must be passed for the input?

thanks!

**Comment by bitmash** [comment]
When you "create a payment" / redirect the user to Alipay's checkout page, you are also sending a `notify_url` with the payload. This URL is a webhook that gets pinged whenever the transaction state changes. 

I believe you want to use their "Single Transaction Query Interface". This library doesn't support it, but it's easy to add. You can read up on it in their documentation.
